### ISSUE TITLE
starttls and smtpmail

### ISSUE THREAD

**Issue by Richard-CAID** [alexmurray/mu-snap#6]
I am using emacs/spacemacs 27.2 and downloaded maildir-utils through my Opensuse Tumbleweed repository. I have mbsync working and emails are syncing into my maildir folders. I finished research/reading on Mu4e configuration and have a basic configuration read to test out. However, I noted an inconsistency regarding starttls and smtpmail.

smtpmail is required by a number of Mu4edotels when sifting through code and starttls is incorporated into Mu4e configuration. However, both of these are not found within a maildir-utils package and are also not found in emacs package lists.

How is this resolved?

**Comment by Richard-CAID** [comment]
Mu4e opens and I can access emails that were synced previously but when I attempt to retrieve emails through Mu4e I receive the following message:
![Message](https://user-images.githubusercontent.com/54129970/119916148-5c26ff00-bf3a-11eb-9e8a-613777535a5e.jpeg)

My dotspacemacs/user-config has the following within make-mu4e- context :var
![Init file_20210527_221828](https://user-images.githubusercontent.com/54129970/119916349-bb850f00-bf3a-11eb-9c15-5d2d26d155bd.jpeg)

Is this a starttsl/smtpmail issue or something else?

**Comment by alexmurray** [comment]
The error is:

gpg decryption failed - and apparently this is due to it not having a gpg agent running - do you have gpg-agent running?

I think these sorts of support requests would be better handled via the mu-discuss mailing list (https://groups.google.com/g/mu-discuss/) or if there are particular issues with mu (which are not specific to the mu snap) then to the mu issue tracker directly (https://github.com/djcb/mu/issues/). Closing this issue as it does not appear to be a specific issue with mu as a snap.
